### ISSUE TITLE
Exception in thread "main" org.multibit.hd.core.exceptions.WalletLoadException: No rolling backup to load from Trezor wallet 

### ISSUE THREAD

**Issue by Christewart** [jim618/multibit#676]
I am getting an error when it comes reloading a wallet I have created from a Trezor. It says that there is no rolling backup created. I am trying to reload the trezor wallet with `getOrCreateTrezorHardWalletSummaryFromRootNode` method. 

    val applicationDirectory = InstallationManager.getOrCreateApplicationDataDirectory
    val walletManager = WalletManager.INSTANCE
    val xpub = "xpub6Fr4fji1QBzdKeEUNa3pxZV3mXD61mwiAwxPqBNEEFJPZHLrXdobYZMb81dLbBbej7ZhzMbbfxEAUuKMpAq3sAsaWR6d2TBHMZFefHR6JtQ"
    val key: DeterministicKey = DeterministicKey.deserializeB58(xpub, network)
    val walletSummary = walletManager.getOrCreateTrezorHardWalletSummaryFromRootNode(applicationDirectory,
      key, creationTime ,"password", "walletId",
      "wallet description", true)

    walletSummary.getWallet

and here is the stack trace

Exception in thread "main" org.multibit.hd.core.exceptions.WalletLoadException: No rolling backup to load
	at org.multibit.hd.core.managers.WalletManager.loadFromWalletDirectory(WalletManager.java:1072)
	at org.multibit.hd.core.managers.WalletManager.getOrCreateTrezorHardWalletSummaryFromRootNode(WalletManager.java:534)
	at Bitcoinj$.reloadWallet(Bitcoinj.scala:40)
	at Bitcoinj$.main(Bitcoinj.scala:26)
	at Bitcoinj.main(Bitcoinj.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.multibit.hd.core.exceptions.WalletLoadException: No rolling backup to load
	at org.multibit.hd.core.managers.BackupManager.loadRollingBackup(BackupManager.java:419)
	at org.multibit.hd.core.managers.WalletManager.loadFromWalletDirectory(WalletManager.java:1049)
	... 9 more

What am I doing wrong, or is there a bug here?

**Comment by Christewart** [comment]
Another error that is occuring as well  : 

18:23:55.674 [main] ERROR o.m.hd.core.managers.WalletManager - WalletManager error: java.lang.IllegalArgumentException No key found for absolute path M/0H/0/0.
java.lang.IllegalArgumentException: No key found for absolute path M/0H/0/0.
	at org.bitcoinj.crypto.DeterministicHierarchy.get(DeterministicHierarchy.java:94) ~[bitcoinj-core-0.13-alice-develop-SNAPSHOT.jar:na]
	at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:774) ~[bitcoinj-core-0.13-alice-develop-SNAPSHOT.jar:na]
	at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:769) ~[bitcoinj-core-0.13-alice-develop-SNAPSHOT.jar:na]
	at org.bitcoinj.wallet.KeyChainGroup.createCurrentKeysMap(KeyChainGroup.java:845) ~[bitcoinj-core-0.13-alice-develop-SNAPSHOT.jar:na]
	at org.bitcoinj.wallet.KeyChainGroup.fromProtobufUnencrypted(KeyChainGroup.java:719) ~[bitcoinj-core-0.13-alice-develop-SNAPSHOT.jar:na]
	at org.bitcoinj.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:420) ~[bitcoinj-core-0.13-alice-develop-SNAPSHOT.jar:na]
	at org.multibit.hd.core.managers.WalletManager.loadWalletFromFile(WalletManager.java:934) [mbhd-core-develop-SNAPSHOT.jar:na]
	at org.multibit.hd.core.managers.WalletManager.loadFromWalletDirectory(WalletManager.java:1038) [mbhd-core-develop-SNAPSHOT.jar:na]
	at org.multibit.hd.core.managers.WalletManager.getOrCreateTrezorHardWalletSummaryFromRootNode(WalletManager.java:534) [mbhd-core-develop-SNAPSHOT.jar:na]
	at Bitcoinj$.reloadWallet(Bitcoinj.scala:38) [classes/:na]
	at Bitcoinj$.main(Bitcoinj.scala:26) [classes/:na]
	at Bitcoinj.main(Bitcoinj.scala) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]

**Comment by jim618** [comment]
Hi Chris,
For your multisig app you can usefully strip away a number of things in the MultiBit HD code. I would recommend eliminating:
+ Backup code
+ The wallet directory structure we use
+ We encrypt the saved wallet with AES 256

The Deterministic Key Chain stuff is fairly complicated code I find so I would recommend avaoiding pulling in MBHD code too.

Try starting with the TrezorWalletTest (i.e. something that is working) and start ripping thngs out piece by piece. If you get to the point where you are not dependent on any MBHD classes (except for a few utility classes perhaps) and only dep on bitcoinj-alice then you're probably good to go.

**Comment by gary-rowe** [comment]
This is a MultiBit HD/Hardware issue and seems to have gone quiet. Closing.
